import { StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
    page: {
      position: "relative",
      padding: "30 50",
      backgroundColor: "transparent",
    },
    background: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    mainContent: {
      position: "relative",
      flexGrow: 1,
      padding: 10,
    },
    title: {
      textAlign: "center",
      padding: "5 10",
      fontSize: 30,
      color: "#4052B5",
      borderWidth: 2,
      borderColor: "#333",
      marginBottom: 10,
      borderRadius: 4,
      backgroundColor: "#ffffff",
      fontFamily: "SpaceGrotesk",
      fontWeight: 1000,
    },
    content: {
      flexDirection: "row",
      gap: 15,
      flexGrow: 1,
    },
    box: {
      borderWidth: 2,
      borderColor: "#333",
      borderRadius: 4,
      backgroundColor: "#ffffff",
    },
    boxHeader: {
      backgroundColor: "#E6E6FA",
      padding: "10 20",
      borderBottomWidth: 2,
      borderBottomColor: "#333",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    headerText: {
      fontSize: 15,
      color: "#4052B5",
      fontFamily: "SpaceGrotesk",
      fontWeight: 500,
    },
    boxContent: {
      padding: 5,
    },
    leftSection: {
      flex: 1,
    },
    rightSection: {
      flex: 2,
    },
    summaryHeader: {
      fontSize: 14,
      fontFamily: "SpaceGrotesk",
      fontWeight: 800,
      color: "#4052B5",
      marginBottom: 2,
      borderBottomWidth: 1,
      borderBottomColor: "#c2c2d6",
    },
    summaryText: {
      marginBottom: 20,
      marginTop: 5,
      fontSize: 10,
      fontFamily: "SpaceGrotesk",
      fontWeight: 500,
    },
    infoRow: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 10,
      padding: "5 8",
      backgroundColor: "#E6E6FA",
      borderRadius: 4,
    },
    infoLabel: {
      fontSize: 10,
      fontFamily: "SpaceGrotesk",
      fontWeight: 700,
      color: "#4052B5",
      width: "40%",
    },
    infoValue: {
      fontSize: 10,
      fontFamily: "SpaceGrotesk",
      fontWeight: 500,
      color: "#333",
      flex: 1,
    },
    attributesText: {
      marginTop: 2,
      fontSize: 10,
      fontFamily: "SpaceGrotesk",
      fontWeight: 500,
    },
    timelineContainer: {
      borderLeftWidth: 2,
      borderLeftColor: "#4052B5",
      marginLeft: 10,
      paddingLeft: 15,
    },
    timelineEvent: {
      marginBottom: 10,
      position: "relative",
    },
    timelineDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: "#4052B5",
      position: "absolute",
      left: -19.5,
      top: 5,
    },
    timelineYear: {
      fontSize: 12,
      fontFamily: "SpaceGrotesk",
      fontWeight: 700,
      color: "#4052B5",
    },
    timelineText: {
      fontSize: 10,
      fontFamily: "SpaceGrotesk",
      fontWeight: 500,
      marginBottom: 10,
    },
    attributesContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      marginBottom: 5,
      gap: 20,
    },
    attributesSection: {
      flex: 1,
    },
    subsectionHeader: {
      fontSize: 12,
      fontFamily: "SpaceGrotesk",
      fontWeight: 700,
      color: "#4052B5",
      marginTop: 10,
      marginBottom: 2,
    },
    deviceContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      marginTop: 5,
    },
    deviceItem: {
      padding: 5,
      backgroundColor: "#E6E6FA",
      borderRadius: 4,
      fontSize: 10,
      fontFamily: "SpaceGrotesk",
    },
    diseaseCard: {
      padding: 8,
      borderRadius: 4,
      marginBottom: 5,
    },
    diseaseText: {
      fontSize: 10,
      fontFamily: "SpaceGrotesk",
      fontWeight: 500,
      color: "#333",
    },
    possibleDiseases: {
      marginTop: 10,
      marginBottom: 10,
    },
    healthConsideration: {
      flexDirection: "row",
      marginBottom: 5,
    },
    bullet: {
      marginRight: 5,
      fontSize: 10,
      fontFamily: "SpaceGrotesk",
    },
  });

export default styles;